version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    ports:
      - "6200:6200"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - SKIP_INGESTION_AND_ANALYSIS=${SKIP_INGESTION_AND_ANALYSIS}
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: weather_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  db_data: