openapi: 3.0.0
info:
  title: Weather API
  version: 1.0.0
paths:
  /api/weather:
    get:
      summary: Get weather records
      parameters:
        - name: station_id
          in: query
          description: Filter by station ID
          required: false
          schema:
            type: string
        - name: start_date
          in: query
          description: Filter records after this date (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: Filter records before this date (YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Items per page
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of weather records
  /api/weather/stats:
    get:
      summary: Get weather statistics
      parameters:
        - name: station_id
          in: query
          description: Filter by station ID
          required: false
          schema:
            type: string
        - name: year
          in: query
          description: Filter statistics by year
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
        - name: per_page
          in: query
          description: Items per page
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paginated list of weather statistics
